project:
  type: website

website:
  title: "Jenna Jacobs: My Data Stories"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
format:
  html:
    theme: morph
    css: styles.css

execute:
  freeze: auto


